name: obeisance
description: Obeisance submissive onboarding client.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.7
  flutter_riverpod: ^2.5.1
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  device_info_plus: ^10.1.2
  battery_plus: ^6.0.2
  uuid: ^4.5.1
  mqtt_client: ^10.5.1
  flutter_background_service: ^5.0.10
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
