name: obeisance
description: Obeisance submissive onboarding client.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.7
  flutter_riverpod: ^2.5.1
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  device_info_plus: ^10.1.2
  battery_plus: ^6.0.2
  uuid: ^4.5.1
  mqtt_client: ^10.5.1
  flutter_background_service: ^5.0.10
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.1
  geolocator: ^13.0.1
  flutter_background_geolocation: ^4.16.8
  network_info_plus: ^6.1.1
  flutter_blue_plus: ^1.34.5
  web_socket_channel: ^3.0.1
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
